objects/AuditLog__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deletion_Type__c</fullName>
        <label>Deletion Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soft Delete</fullName>
                </value>
                <value>
                    <fullName>Hard Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AuditLog</label>
    <nameField>
        <label>AuditLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditLog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MemberExt.cls
public  with sharing class MemberExt {
    
    public List<AuditLog__c> auditList {get;set;}
    private ApexPages.StandardSetController standardController;
    private Set<Id> auditIds = new Set<Id>();
    
    public MemberExt(ApexPages.StandardSetController standardController){
        
        this.standardController = standardController;
        auditList = new List<AuditLog__c>();
        
        for (AuditLog__c auditObj : (List<AuditLog__c>)standardController.getSelected()){ 
            auditIds.add(auditObj.Id);
            
        }
        
        auditList = [SELECT Id, Name, Action__c,Deletion_Type__c,CreatedDate FROM AuditLog__c WHERE ID IN: auditIds WITH SECURITY_ENFORCED];
        
    }
    
}