objects/Change_Request__c.object
<CustomObject>
    <description>This object is to track the service-now change request.</description>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Backout_Plan__c</fullName>
        <defaultValue>&quot;Usine Copado roll out plan&quot;</defaultValue>
        <label>Backout Plan</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>System Software</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Request__c</fullName>
        <formula>HYPERLINK(&quot;https://dev177258.service-now.com/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D&quot;&amp; System_ID__c &amp;&quot;%26sysparm_view%3D&quot;,CR_Number__c)</formula>
        <label>View in SNOW</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 - High</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 - Medium</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 - Low</label>
                </value>
                <value>
                    <fullName>Localized</fullName>
                    <default>true</default>
                    <label>Localized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Plan__c</fullName>
        <defaultValue>&quot;Deployment using Copado during off business hours&quot;</defaultValue>
        <label>Implementation Plan</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 - Critical</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 - High</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 - Moderate</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <default>true</default>
                    <label>4 - Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release_LookUp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release LookUp</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Impact_Analysis__c</fullName>
        <defaultValue>&quot;No risk associated&quot;</defaultValue>
        <label>Risk Impact Analysis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>High</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Moderate</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <defaultValue>&quot;Salesforce production deployment&quot;</defaultValue>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_ID__c</fullName>
        <externalId>true</externalId>
        <label>System ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Test_Plan__c</fullName>
        <defaultValue>&quot;PO/BA Validate post deployment&quot;</defaultValue>
        <label>Test Plan</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>emergency</fullName>
                    <label>Emergency</label>
                </value>
                <value>
                    <fullName>standard</fullName>
                    <label>Standard</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>justification__c</fullName>
        <defaultValue>&quot;Sev1 prod defects deployment&quot;</defaultValue>
        <label>Justification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Jira_Key__c</fullName>
        <label>Jira Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/snow_updatedescription.cls
global class snow_updatedescription{

    Public static void updatedescription(id crid){
        Change_Request__c cr = [SELECT Id,Name,Impact__c,Category__c,Description__c,justification__c,Risk__c,
                                    Priority__c,Risk_Impact_Analysis__c,Short_Description__c,Type__c,Implementation_Plan__c,Release_LookUp__c,
                                    Backout_Plan__c,Test_Plan__c,Planned_End_Date__c,Planned_Start_Date__c,Actual_Start_Date__c,Actual_End_Date__c,System_ID__c
                                    FROM Change_Request__c  Where id =:crid];

        String combinedDescription;
        String lineBreak = '\\r\\n';
            if (cr != null) {
                    Id rel_id = cr.Release_LookUp__c;
                    List<String> userStoryDescriptions = new List<String>();
                                        
                        List<copado__User_Story__c> cusList = [SELECT Id, Name,Jira_Key__c, copado__User_Story_Title__c, copado__Release__c
                                        FROM copado__User_Story__c WHERE copado__Release__c = :rel_id];
                                        
                        for (copado__User_Story__c cus : cusList) {
                            String userStoryDescription = cus.Jira_Key__c + ' - ' + cus.copado__User_Story_Title__c;
                            system.debug('userStoryDescription ====='+userStoryDescription);
                            userStoryDescriptions.add(userStoryDescription);
                            }
                            cr.description__C=null;
                        for(String ud : userStoryDescriptions){
                            cr.Description__c = cr.Description__c!=null? cr.Description__c+'<br>'+ud:ud;
                            system.debug('cr.description__C===='+cr.description__C);
                        }    

                                        
                            // Combine userStoryDescriptions into a single description
                           //combinedDescription = 
                            System.debug('userStoryDescriptions ========='+userStoryDescriptions);
                            // Update the Description__c field of the Change Request
                            //cr.Description__c = combinedDescription;
                            update cr;
                } 
    }
}