objects/ChartObject__c.object
<CustomObject>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ChartObject</label>
    <nameField>
        <label>ChartObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChartObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Data_Template__c.object
<CustomObject>
    <label>Data Template</label>
    <nameField>
        <label>Data Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>copado__Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Function__c.object
<CustomObject>
    <description>A function is a script that contains a series of commands and can be executed from Copado.</description>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__OrgDiff__c.object
<CustomObject>
    <label>Org Difference</label>
    <nameField>
        <label>Org Difference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Differences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Is_Rolled_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Rolled Back?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Static_Code_Analysis_Result__c.object
<CustomObject>
    <description>This object stores the results of Static Code Analysis executed through Copado.</description>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Static Code Analysis Results</relationshipLabel>
        <relationshipName>Static_Code_Analysis_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Static Code Analysis Result</label>
    <nameField>
        <displayFormat>SCA-{00000}</displayFormat>
        <label>Static Code Analysis Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Static Code Analysis Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Exclude_From_CBM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this user story will not be included in the count of user stories ahead and behind.</description>
        <inlineHelpText>If checked, this user story will not be included in the count of user stories ahead and behind.</inlineHelpText>
        <label>Exclude from Pipelines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Is_Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bundle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>TO DO</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>SELECTED FOR DEVELOPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Exclude from Overlap Awareness</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ChartObjectQuery.cls
global class ChartObjectQuery implements Schedulable{
    global static void execute(SchedulableContext sc){
        Integer users = [select count() from User];
        
        List<ChartObject__c> records = [SELECT Name from ChartObject__c ORDER BY Name ASC];
        for(ChartObject__c rec : records ){
            if(rec.Name == 'Copado Functions'){
                List<copado__Function__c> useList = [select LastModifiedById from copado__Function__c ];
                Set<Id> use = New Set<Id>();
                for(copado__Function__c us : useList){
                    use.add(us.LastModifiedById);
                }
                system.debug(use.size());
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Function__c ];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Data Templates'){
                List<copado__Data_Template__c> useList = [select LastModifiedById from copado__Data_Template__c ];
                Set<Id> use = New Set<Id>();
                for(copado__Data_Template__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Data_Template__c ];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Deployments'){
                List<copado__Deployment__c> useList = [select LastModifiedById from copado__Deployment__c where copado__Status__c = 'Completed Successfully' ];
                Set<Id> use = New Set<Id>();
                for(copado__Deployment__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Deployment__c where copado__Status__c = 'Completed Successfully' ];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Exclude Completed Stories'){
                List<copado__User_Story__c> useList = [select LastModifiedById from copado__User_Story__c  where copado__Exclude_From_CBM__c = TRUE AND copado__Stop_Indexing_Metadata__c = true ];
                Set<Id> use = New Set<Id>();
                for(copado__User_Story__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__User_Story__c  where copado__Exclude_From_CBM__c = TRUE AND copado__Stop_Indexing_Metadata__c = true];
            	system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Org Differences'){
                List<copado__OrgDiff__c> useList = [select LastModifiedById from copado__OrgDiff__c ];
                Set<Id> use = New Set<Id>();
                for(copado__OrgDiff__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__OrgDiff__c];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Promotions'){
                List<copado__Promotion__c> useList = [select LastModifiedById from copado__Promotion__c where copado__Status__c = 'Completed' ];
                Set<Id> use = New Set<Id>();
                for(copado__Promotion__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Promotion__c where copado__Status__c = 'Completed'];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Rollback Feature'){
                List<copado__Promotion__c> useList = [select LastModifiedById from copado__Promotion__c where copado__Is_Rolled_Back__c = true];
                Set<Id> use = New Set<Id>();
                for(copado__Promotion__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Promotion__c where copado__Is_Rolled_Back__c = true];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Snapshot Differences'){
                List<copado__Snapshot_Difference__c> useList = [select LastModifiedById from copado__Snapshot_Difference__c ];
                Set<Id> use = New Set<Id>();
                for(copado__Snapshot_Difference__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Snapshot_Difference__c];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'Static Code Analysis'){
                List<copado__Static_Code_Analysis_Result__c> useList = [select LastModifiedById from copado__Static_Code_Analysis_Result__c ];
                Set<Id> use = New Set<Id>();
                for(copado__Static_Code_Analysis_Result__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Static_Code_Analysis_Result__c];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'User Stories'){
                List<copado__User_Story__c> useList = [select LastModifiedById from copado__User_Story__c ];
                Set<Id> use = New Set<Id>();
                for(copado__User_Story__c us : useList){
                    use.add(us.LastModifiedById);
                }
                system.debug(use.size());
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__User_Story__c];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'User Story Bundles'){
                List<copado__User_Story__c> useList = [select LastModifiedById from copado__User_Story__c where copado__Is_Bundle__c=true];
                Set<Id> use = New Set<Id>();
                for(copado__User_Story__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__User_Story__c where copado__Is_Bundle__c=true];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
            if(rec.Name == 'User Story Dependencies'){
                List<copado__Team_Dependency__c> useList = [select LastModifiedById from copado__Team_Dependency__c ];
                Set<Id> use = New Set<Id>();
                for(copado__Team_Dependency__c us : useList){
                    use.add(us.LastModifiedById);
                }
                rec.X__c = ((Double) use.size()/users)*100;
                rec.Y__c = [select count() from copado__Team_Dependency__c];
                system.debug(rec.X__c);
                system.debug(rec.Y__c);
            }
        }
        update records;
    }
    @AuraEnabled(cacheable=true)
    public static string warnScheduled(){
        String empString = 'empty';
        List<CronTrigger> crtrigger = [SELECT CronJobDetail.Name FROM CronTrigger Where CronJobDetail.Name = 'Schedule Chart'];
        if(crtrigger.size()!= 0){
            for(CronTrigger cr : crtrigger){
                if(cr.CronJobDetail.Name == 'Schedule Chart'){
                    empString = cr.CronJobDetail.Name;
                }
            }
            return empString;
        }
        else return empString;
    }
    
}