objects/ChartObject__c.object
<CustomObject>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ChartObject</label>
    <nameField>
        <label>ChartObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChartObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>copado__Promotion__r.copado__Platform__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>TEXT(copado__Deployment_Flow__r.copado__Platform__c)</formula>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__API_Name__c</fullName>
        <description>Use this field as an identifier for the Environment record when referencing it in an action.</description>
        <inlineHelpText>Use this field as an identifier for the Environment record when referencing it in an action.</inlineHelpText>
        <label>API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Function__c.object
<CustomObject>
    <description>A function is a script that contains a series of commands and can be executed from Copado.</description>
    <fields>
        <fullName>copado__API_Name__c</fullName>
        <description>Provide a unique API name.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique name that identifies this function. The function result records will contain this API Name in the job type field for filtering these results in reports and dashboards.</inlineHelpText>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Disable_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this checkbox will not validate the org credentials when the record is saved or viewed.</inlineHelpText>
        <label>Disable Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>TEXT(copado__Environment__r.copado__Platform__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__API_Name__c</fullName>
        <description>Use this field as an identifier for the Project record when referencing it in an action.</description>
        <inlineHelpText>Use this field as an identifier for the Project record when referencing it in an action.</inlineHelpText>
        <label>API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <formula>IF( NOT(ISBLANK( copado__Project__c )) ,  TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  IF( NOT(ISBLANK( copado__Release__c )),  TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) , &apos;Salesforce&apos;) )</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform.</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Static_Code_Analysis_Result__c.object
<CustomObject>
    <description>This object stores the results of Static Code Analysis executed through Copado.</description>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Static Code Analysis Results</relationshipLabel>
        <relationshipName>Static_Code_Analysis_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Static Code Analysis Result</label>
    <nameField>
        <displayFormat>SCA-{00000}</displayFormat>
        <label>Static Code Analysis Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Static Code Analysis Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Exclude_From_CBM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this user story will not be included in the count of user stories ahead and behind.</description>
        <inlineHelpText>If checked, this user story will not be included in the count of user stories ahead and behind.</inlineHelpText>
        <label>Exclude from Pipelines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Is_Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bundle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Platform__c</fullName>
        <description>This field auto-populates and displays the pipeline platform</description>
        <formula>BLANKVALUE( 
    TEXT(copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c) ,  
    BLANKVALUE(  
        TEXT(copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Platform__c), 
        &apos;&apos;
    ) 
)</formula>
        <inlineHelpText>This field auto-populates and displays the pipeline platform</inlineHelpText>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Exclude from Overlap Awareness</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FeatureAuditTest.cls
@isTest
private class FeatureAuditTest {
    @testSetup
    static void testSetup(){
    List<ChartObject__c> coList = New List<ChartObject__c>();
    ChartObject__C co1 = New ChartObject__c();
    co1.Name = 'Automation Template';
    co1.X__c = 20;
    co1.Y__c = 30;
    coList.add(co1);
    ChartObject__C co2 = New ChartObject__c();
    co2.Name = 'Copado Functions';
    co2.X__c = 0;
    co2.Y__c = 0;
    coList.add(co2);
        ChartObject__C co3 = New ChartObject__c();
    co3.Name = 'Data Templates';
    co3.X__c = 0;
    co3.Y__c = 0;
    coList.add(co3);
        ChartObject__C co4 = New ChartObject__c();
    co4.Name = 'Deployments';
    co4.X__c = 0;
    co4.Y__c = 0;
    coList.add(co4);
        ChartObject__C co5 = New ChartObject__c();
    co5.Name = 'Exclude Completed Stories';
    co5.X__c = 0;
    co5.Y__c = 0;
    coList.add(co5);
        ChartObject__C co6 = New ChartObject__c();
    co6.Name = 'Org Differences';
    co6.X__c = 0;
    co6.Y__c = 0;
    coList.add(co6);
        ChartObject__C co7 = New ChartObject__c();
    co7.Name = 'Promotions';
    co7.X__c = 0;
    co7.Y__c = 0;
    coList.add(co7);
        ChartObject__C co8 = New ChartObject__c();
    co8.Name = 'Rollback Feature';
    co8.X__c = 0;
    co8.Y__c = 0;
    coList.add(co8);
        ChartObject__C co9 = New ChartObject__c();
    co9.Name = 'Snapshot Differences';
    co9.X__c = 0;
    co9.Y__c = 0;
    coList.add(co9);
        ChartObject__C co10 = New ChartObject__c();
    co10.Name = 'Static Code Analysis';
    co10.X__c = 0;
    co10.Y__c = 0;
    coList.add(co10);
        ChartObject__C co11 = New ChartObject__c();
    co11.Name = 'User Stories';
    co11.X__c = 0;
    co11.Y__c = 0;
    coList.add(co11);
        ChartObject__C co12 = New ChartObject__c();
    co12.Name = 'User Story Bundles';
    co12.X__c = 0;
    co12.Y__c = 0;
    coList.add(co12);
        ChartObject__C co13 = New ChartObject__c();
    co13.Name = 'User Story Dependencies';
    co13.X__c = 0;
    co13.Y__c = 0;
    coList.add(co13);
    insert coList;
        copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
        copado.GlobalAPI.UserLicense UL = new copado.GlobalAPI.UserLicense();
        UL.isCADEnabled = false;
        UL.isCCHEnabled = false;
        UL.isCCMEnabled = true;
        UL.isCopadoEnabled = true;
        UL.isCSTEnabled = false;
        UL.userId = userInfo.getUserId();
        copado.GlobalAPI.LicenseOperationResult result = copadoGlobalAPI.upsertCopadoLicense(UL);
        if(result.isSuccess){
            System.debug('License assigned successfully');
        }
        else {
            System.debug('An error occurred during license assignment with the error message ' + result.errorString);
        }
        
        /*copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
        copado.GlobalAPI.UserLicense UL = new copado.GlobalAPI.UserLicense();
        UL.isCADEnabled = false; //Agile delivery license
        UL.isCCHEnabled = false; //Compliance hub license
        UL.isCCMEnabled = true; //Change management (developer) license
        UL.isCopadoEnabled = true; //Enterprise (admin / release manager) license
        //UL.isCSTEnabled = true; //Copado Selenium testing license
        UL.userId = UserInfo.getUserId();
        copado.GlobalAPI.LicenseOperationResult result = copadoGlobalAPI.upsertCopadoLicense(UL);
        if(result.isSuccess){
            System.debug('License assigned successfully');
        } else {
            System.debug('An error occurred during license assignment with the error message ' + result.errorString);
        }
        */
        copado__Function__c cf = New copado__Function__c();
        cf.Name = 'Test Function';
        cf.copado__API_Name__c = 'Run_Checkmarx_QIF_1';
        insert cf;
        
        copado__Data_Template__c cd = New copado__Data_Template__c();
        cd.Name = 'Test Data Template';
        insert cd;
        
        copado__Deployment__c cdo = New copado__Deployment__c();
        cdo.Name = 'Test Deployment';
        insert cdo;
        
        copado__User_Story__c cu = New copado__User_Story__c();
        cu.copado__User_Story_Title__c = 'Test UserStory';
        cu.copado__Exclude_From_CBM__c = TRUE;
        cu.copado__Stop_Indexing_Metadata__c = true;
        cu.copado__Is_Bundle__c=true;
        insert cu;
        
        copado__Environment__c objEnvi1 = new copado__Environment__c(Name='TRNDEV1',copado__Platform__c='Salesforce');
        insert objEnvi1;
        
        copado__Environment__c objEnvi2 = new copado__Environment__c(Name='TRNQA',copado__Platform__c='Salesforce');
        insert objEnvi2;
        
        copado__Org__c objCredential1 = new copado__Org__c (Name='TRNDEV1',	copado__Org_Type__c='Sandbox' ,copado__Disable_Validation__c=true,copado__Environment__c = objEnvi1.Id);
        insert objCredential1;
        
        copado__Org__c objCredential2 = new copado__Org__c (Name='TRNQA',	copado__Org_Type__c='Sandbox' ,copado__Disable_Validation__c=true,copado__Environment__c = objEnvi2.Id);
        insert objCredential2;
        
        copado__OrgDiff__c cod = New copado__OrgDiff__c();
        cod.Name = 'Test Org';
        cod.copado__From_Org__c = objCredential1.Id;
        cod.copado__To_Org__c = objCredential2.Id;
        insert cod;
        
        //Create Pipeline
        copado__Deployment_Flow__c objPipeline = new copado__Deployment_Flow__c(Name= 'Test Pipeline Name',copado__Active__c = true,copado__Platform__c ='Salesforce'/*,copado__Deployment_Automation__c =objDep1.Id*/);
        insert objPipeline;
        
        //CREATE PIPELINE CONNECTIONS
        copado__Deployment_Flow_Step__c objPipConn = new copado__Deployment_Flow_Step__c(copado__Deployment_Flow__c = objPipeline.Id,	copado__Source_Environment__c=objEnvi1.Id, 	copado__Destination_Environment__c=objEnvi2.Id,	copado__Branch__c='trndev1');
        insert objPipConn;
        
        //CREATE PROJECT
        copado__Project__c objProject= new copado__Project__c(Name='Test Project Name',copado__Deployment_Flow__c=objPipeline.Id);
        insert objProject;
        
        copado__Promotion__c cp = New copado__Promotion__c();
        cp.copado__Is_Rolled_Back__c = true;
        cp.copado__Status__c = 'Completed';
        cp.copado__Project__c = objProject.Id;
        cp.copado__Source_Environment__c = objEnvi1.Id;
        cp.copado__Destination_Environment__c = objEnvi2.Id;
        insert cp;
        
        copado__Snapshot_Difference__c cs = New copado__Snapshot_Difference__c();
        cs.Name = 'Test Snapshot';
        insert cs;
        
        copado__Static_Code_Analysis_Result__c csc = New copado__Static_Code_Analysis_Result__c();
        csc.copado__Details__c = 'Test Static Code';
        insert csc;
        
        copado__Team_Dependency__c ct = New copado__Team_Dependency__c();
        ct.copado__Provider_User_Story__c = cu.Id;
        ct.copado__Dependent_User_Story__c = cu.Id;
        insert ct;
        
        copado__Deployment__c objDep1 = New copado__Deployment__c(Name='depName1',copado__From_Org__c=objCredential1.Id, copado__Status__c = 'Completed Successfully');
        insert objDep1;
        
        }
    
    @isTest
    static void fAT1(){
        Test.startTest();
        Map<String,ChartObject__c> check1 = ChartWire.getName();
        ChartObject__c cobj = check1.get('x0');
        //ChartObject__c fetchedData = [SELECT Name from ChartObject__c ORDER BY Name ASC LIMIT 1];
        System.assert(cobj.Name == 'Automation Template');
        Test.stopTest();
    }
    @isTest
    static void fAT2(){
        Test.startTest();
        List<ChartObject__c> check1 = ChartWire.getEmpty();
        ChartObject__c fetchedData = [SELECT Name,X__c, Y__c from ChartObject__c Where X__c = 0 AND Y__c =0 ORDER BY Name ASC Limit 1];
        System.assert(check1[0].Name == fetchedData.Name);
        Test.stopTest();
    }
    @isTest
    static void fAT3(){
        Test.startTest();
        ChartObjectQuery coq = New ChartObjectQuery();
        string sch = '0 0 6 * * ? *';
        System.schedule('TestJob', sch, coq);
        CronTrigger crt = [SELECT CronJobDetail.Name FROM CronTrigger Where CronJobDetail.Name = 'TestJob' LIMIT 1];
        system.assert(crt.CronJobDetail.Name == 'TestJob');
        Test.stopTest();
    }
    @isTest
    static void fAT4(){
        Test.startTest();
        ChartObjectQuery obj = New ChartObjectQuery();
        String sch = '0 0 6 * * ? *';
        System.schedule('Schedule Chart', sch, obj);
        String chk2 = ChartObjectQuery.warnScheduled();
        CronTrigger crt = [SELECT Id, CronJobDetail.Name FROM CronTrigger Where CronJobDetail.Name = 'Schedule Chart' LIMIT 1];
        if( crt != null){
            System.assert(chk2 != 'empty');
        }
        /*String chk1 = ChartObjectQuery.warnScheduled();
        System.assert(chk1=='empty');
        Test.stopTest();*/
    }
    @isTest
    static void fAT5(){
        Test.startTest();
        String jobid = ScheduleChart.scheduled();
        CronTrigger crt = [SELECT Id, CronJobDetail.Name FROM CronTrigger Where CronJobDetail.Name = 'Schedule Chart' LIMIT 1];
        if( crt != null){
            System.assert(jobid == crt.Id);
        }
        String jobid2 = ScheduleChart.scheduled();
        System.assert(jobid2 == 'Dont Allow');
        Test.stopTest();
        }
    /*@isTest
    static void fAT6(){
        //Before running, ensure that RemoveScheduledChart is already scheduled. Else, it will not have code coverage.
        Test.startTest();
        RemoveScheduledChart coq = New RemoveScheduledChart();
        string sch = '0 3 6 * * ? *';
        System.schedule('TestJob1', sch, coq);
        Test.stopTest();
    }*/
    
    
}