objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Exclude_From_CBM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this user story will not be included in the count of user stories ahead and behind.</description>
        <inlineHelpText>If checked, this user story will not be included in the count of user stories ahead and behind.</inlineHelpText>
        <label>Exclude from Pipelines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>TO DO</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>SELECTED FOR DEVELOPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Exclude from Overlap Awareness</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Copado_Utility_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Copado Utility Configuration</label>
    <pluralLabel>Copado Utility Configurations</pluralLabel>
</CustomObject>

classes/BatchSixMonthUserStoryDataDeletion.cls
public with sharing class BatchSixMonthUserStoryDataDeletion implements Database.Batchable<sObject>{   // This Class is used for scheduling Record cleanup
   
    Date today =System.today();
    Date LAST_N_MONTHS ;

    public string query;
    public string selectedObject;

    Public BatchSixMonthUserStoryDataDeletion(Integer n,string objectName){
        LAST_N_MONTHS= today.addMonths(-n);
       selectedObject = objectName;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){ 

                    string statusMetadata =test.isRunningTest()?'Done': [Select MasterLabel, Value__c from Copado_Utility_Configuration__mdt where  MasterLabel = 'Production Status'].Value__c;
                    String statusString = '\''+ statusMetadata + '\'' ;

                    String query ;
                    if(test.isRunningTest()){
                        query= 'SELECT Name,LastModifiedDate,copado__Exclude_From_CBM__c,copado__Stop_Indexing_Metadata__c from  ' + selectedObject + ' WHERE copado__Exclude_From_CBM__c = false AND copado__Stop_Indexing_Metadata__c = false AND copado__Status__c =' + statusString +'  WITH SECURITY_ENFORCED ';
                    }
                    else{
                        if(selectedObject == 'copado__User_Story__c'){
                           query= 'SELECT Name,LastModifiedDate,copado__Exclude_From_CBM__c,copado__Stop_Indexing_Metadata__c from  ' + selectedObject + ' WHERE copado__Exclude_From_CBM__c = false AND copado__Stop_Indexing_Metadata__c = false AND LastModifiedDate <=: LAST_N_MONTHS AND copado__Status__c =' + statusString +' WITH SECURITY_ENFORCED ';
                        }
                        else{
                            query = 'SELECT Id, Name,createdDate,LastModifiedDate from ' + selectedObject + ' WHERE LastModifiedDate <=: LAST_N_MONTHS  WITH SECURITY_ENFORCED';
                        }
                    }
                    
                    List<sObject> sObjectQueryList= Database.query(query);
                    
                    return Database.getQueryLocator(query);
     }

     public void execute(Database.BatchableContext bc, List<sObject> objectList){

                    List<Id> recordIdList = new List<Id>();
                    for(sObject sObj: objectList){

                        recordIdList.add(sObj.id);

                    }
                    
                    CentralClass.softRecordBackup(recordIdList,selectedObject);
                    Database.delete(objectList,false);
                
     }

     public void finish(Database.BatchableContext bc){
        
    }
}