objects/copado__Git_Backup__c.object
<CustomObject>
    <description>A Git Snapshot record in Copado defines a connection between a Salesforce Org with a Git Repository/branch.</description>
    <fields>
        <fullName>copado__Branch__c</fullName>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Git branch related to the Org. Be aware that branch names are case sensitive.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BranchesExcluded.cls
public class BranchesExcluded {
    @AuraEnabled(cacheable=true)
    public static List<copado__Git_Repository__c> repo(){
        List<copado__Git_Repository__c> rep = [Select Id, Name from copado__Git_Repository__c];
        return rep;
    }
    @AuraEnabled
    public static List<copado__Git_Backup__c> branchesExcluded(ID repo){
		List<copado__Git_Backup__c> branches = [Select Id, Name, copado__Git_Repository__c,copado__Branch__c from copado__Git_Backup__c 
                                                where  copado__Git_Repository__c=: repo];        
    	return branches;
    }

}