objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Metadata_Types_in_Selection__c</fullName>
        <description>Metadata types of the components listed in the User Story Selections. This value is updated automatically by Copado.</description>
        <inlineHelpText>Metadata types of the components listed in the User Story Selections. This value is updated automatically by Copado.</inlineHelpText>
        <label>Metadata Types in Selection</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ActionLinkGroupTemplate</fullName>
                </value>
                <value>
                    <fullName>AnalyticSnapshot</fullName>
                </value>
                <value>
                    <fullName>ApexClass</fullName>
                </value>
                <value>
                    <fullName>ApexComponent</fullName>
                </value>
                <value>
                    <fullName>ApexPage</fullName>
                </value>
                <value>
                    <fullName>ApexTrigger</fullName>
                </value>
                <value>
                    <fullName>AppMenu</fullName>
                </value>
                <value>
                    <fullName>ApprovalProcess</fullName>
                </value>
                <value>
                    <fullName>AssignmentRule</fullName>
                </value>
                <value>
                    <fullName>AssignmentRules</fullName>
                </value>
                <value>
                    <fullName>AuraDefinitionBundle</fullName>
                </value>
                <value>
                    <fullName>AuthProvider</fullName>
                </value>
                <value>
                    <fullName>AutoResponseRule</fullName>
                </value>
                <value>
                    <fullName>AutoResponseRules</fullName>
                </value>
                <value>
                    <fullName>BusinessProcess</fullName>
                </value>
                <value>
                    <fullName>CallCenter</fullName>
                </value>
                <value>
                    <fullName>Certificate</fullName>
                </value>
                <value>
                    <fullName>ChannelLayout</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>CompactLayout</fullName>
                </value>
                <value>
                    <fullName>ConnectedApp</fullName>
                </value>
                <value>
                    <fullName>CorsWhitelistOrigin</fullName>
                </value>
                <value>
                    <fullName>CustomApplication</fullName>
                </value>
                <value>
                    <fullName>CustomField</fullName>
                </value>
                <value>
                    <fullName>CustomLabel</fullName>
                </value>
                <value>
                    <fullName>CustomLabels</fullName>
                </value>
                <value>
                    <fullName>CustomMetadata</fullName>
                </value>
                <value>
                    <fullName>CustomObject</fullName>
                </value>
                <value>
                    <fullName>CustomObjectTranslation</fullName>
                </value>
                <value>
                    <fullName>CustomPageWebLink</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>TO DO</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>SELECTED FOR DEVELOPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>copado__Metadata_API_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Type of the metadata</description>
        <inlineHelpText>Type of the metadata</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SharedComponentMatrixClassTest.cls
@isTest
public class SharedComponentMatrixClassTest {
    
    @testSetup
    static void setup() {
        List<copado__Environment__c> envs = new List<copado__Environment__c>();
        envs.add(new copado__Environment__c(Name='Production', copado__Type__c='Production/Developer'));
        envs.add(new copado__Environment__c(Name='Sandbox', copado__Type__c='Sandbox'));
        
        List<copado__user_Story__c> userStories = new List<copado__user_Story__c>();
       
        for (copado__Environment__c env : envs) {
            userStories.add(new copado__user_Story__c(copado__User_Story_Title__c = 'Test User Story', copado__Environment__c = env.Id,
                                                      copado__Metadata_Types_in_Selection__c = 'CustomObject'));
            
        }
        insert userStories;
        
        List<copado__User_Story_Metadata__c> metadataList = new List<copado__User_Story_Metadata__c>();
        for(copado__User_Story__c story : userStories) {
            copado__User_Story_Metadata__c metadata = new copado__User_Story_Metadata__c(
                Name = 'Test Metadata',
                copado__User_Story__c = story.Id,
                copado__Metadata_API_Name__c = 'Account.Poc__c',
                copado__Status__c = 'Potential Conflict'
               );
            metadataList.add(metadata);
        }
        insert metadataList;
        for(copado__User_Story_Metadata__c metadata : metadataList){
            Test.setCreatedDate(metadata.Id, Date.today().addDays(-10));
        }
    }
    
    @isTest
    static void testControllerMethod() {
        
        ApexPages.currentPage().getParameters().put('days', '10');
        ApexPages.currentPage().getParameters().put('fromDt', '2023-01-01');
        ApexPages.currentPage().getParameters().put('toDt', '2023-01-10');

        // Call the static method directly on the class
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.matrix(10, Date.valueOf('2023-01-01'), Date.valueOf('2023-01-10'));

        // Perform assertions to validate the results
        // For example, assert that the result is not null, or check specific properties of the result
        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size()); // Adjust this based on the expected result size or content

        // Add more assertions as needed based on the logic in your controller method
    }
    
    @isTest static void testMatrixWithDaysNotNull() {
        Integer days = 10;
        Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.matrix(null, null, null);
        Test.stopTest();
        Assert.isNotNull(result);
    }

    @isTest static void testMatrixWithFromDateToDateNotNull() {
        Date fromDate = Date.newInstance(2023, 10,11 );
        Date toDate = System.Today();
        Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.matrix(null, fromDate, toDate);
        Test.stopTest();
        Assert.areEqual(result.size(),1);
    }

    
    @isTest static void testSearchKeyWithDaysAndSearchKey() {
      	Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.searchKey('Test', 10, null, null);
        Test.stopTest();
        Assert.areEqual(result.size(),1);
      
    }

    @isTest static void testSearchKeyWithDaysAndNoSearchKey() {
        Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.searchKey(null, 10, null, null);
        Test.stopTest();
        Assert.areEqual(result.size(),0);
     
    }

    @isTest static void testSearchKeyWithDateRangeAndSearchKey() {
     
        Date fromDt = Date.newInstance(2023, 10,11 );
        Date toDt = System.Today();
        Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.searchKey('Test', null, fromDt, toDt);
        Test.stopTest();
        Assert.areEqual(result.size(),1);
    
    }

    @isTest static void testSearchKeyWithDateRangeAndNoSearchKey() {
   
        DateTime fromDt = DateTime.newInstance(2023, 1, 1, 0, 0, 0);
        DateTime toDt = System.now();
        Test.startTest();
        List<SharedComponentMatrixClass.Wrapper> result = SharedComponentMatrixClass.searchKey(null, null, fromDt, toDt);
        Test.stopTest();
        Assert.areEqual(result.size(),0);
    }
}