objects/copado__Git_Backup__c.object
<CustomObject>
    <description>A Git Snapshot record in Copado defines a connection between a Salesforce Org with a Git Repository/branch.</description>
    <fields>
        <fullName>Repository_Name__c</fullName>
        <formula>copado__Git_Repository__r.Name</formula>
        <label>Repository Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Branch__c</fullName>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Git branch related to the Org. Be aware that branch names are case sensitive.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BranchExclusion.cls
public with sharing class BranchExclusion {
    @AuraEnabled(cacheable=true)
    public static List<copado__Git_Backup__c> getBranches(){
        Map<String,copado__Git_Backup__c> branchmap = new Map<String,copado__Git_Backup__c>();
        List<copado__Git_Backup__c> blist = new List<copado__Git_Backup__c>();
        try{
            blist = [select id,name,copado__Branch__c,copado__Git_Repository__r.name,Repository_Name__c from copado__Git_Backup__c];
            for(copado__Git_Backup__c cgb : blist){
                branchmap.put(cgb.Repository_Name__c+cgb.copado__Branch__c,cgb);
            }
            return branchmap.values();
         }
         catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }    
}