objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>copado__Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <formula>copado__From_Org__r.copado__Environment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source Environment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>copado__Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>copado__Promotion__c</referenceTo>
        <relationshipLabel>Promoted User Stories</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
        <label>Active / Outdated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Outdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>No_of_Bug_Fixes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No. of Bug Fixes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>TO DO</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
                <value>
                    <fullName>SELECTED FOR DEVELOPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/deploymentTriggerHelper.cls
public class deploymentTriggerHelper {
    
    public static void afterUpdate(List<copado__Deployment__c> depList){
        
        system.debug('Deployment Trigger');
        //Create Promotion Id set
        Set<Id> promIdSet = new Set<Id>();
        
        for(copado__Deployment__c objDep : depList){
            system.debug('Deployment is ='+objDep);
            if(objDep.copado__Status__c == 'Completed Successfully'){
                promIdSet.add(objDep.copado__Promotion__c); 
            }
        } 
        
        system.debug('promIdSet is ='+promIdSet);
        
        //Create User Story Id set
        Set<Id> USIdSet = new Set<Id>();
        
        if(!promIdSet.isEmpty()){
            for(copado__Promoted_User_Story__c objPromUs : [select Id,	copado__User_Story__c,copado__Promotion__c from copado__Promoted_User_Story__c where copado__Promotion__c IN : promIdSet]){
                USIdSet.add(objPromUs.copado__User_Story__c);
            }
        }
        
        system.debug('USIdSet is ='+USIdSet);
        
        //Group all Promotions related to User Story
        Set<Id> allPromIdSet = new Set<Id>();
        if(!USIdSet.isEmpty()){
            for(copado__Promoted_User_Story__c objPromUs : [select Id,	copado__Promotion__c,copado__User_Story__c from copado__Promoted_User_Story__c where copado__User_Story__c IN : USIdSet]){
                allPromIdSet.add(objPromUs.copado__Promotion__c);
            }
        }
        system.debug('allPromIdSet  = '+allPromIdSet);
        system.debug('allPromIdSet size = '+allPromIdSet.size());
        
        
        map<String, integer> promMap = new map<String, integer>();
        integer count;
        
        if(!allPromIdSet.isEmpty()){
            
            for(copado__Deployment__c objDep : [SELECT Id, Name, copado__Status__c, copado__Promotion__c,copado__Promotion__r.copado__Source_Environment__r.name,copado__Promotion__r.copado__Destination_Environment__r.name FROM copado__Deployment__c where copado__Status__c='Completed Successfully'	and copado__Promotion__c IN : allPromIdSet]){
                
                String credential = objDep.copado__Promotion__r.copado__Source_Environment__r.name +' - '+ objDep.copado__Promotion__r.copado__Destination_Environment__r.name;
                system.debug('credential = '+credential);
                if(promMap.containsKey(credential)){
                    count = promMap.get(credential)+1;
                    promMap.put(credential, count);
                }
                else{
                    promMap.put(credential, 0);
                }
            }
        }
        
        system.debug('promMap is ='+promMap);
        
        Integer finalcount=0;
        for(Integer i : promMap.values()){
            finalcount+=i;
        }
        
        system.debug('finalcount is ='+finalcount);
        
        
        List<copado__User_Story__c> usList = New List<copado__User_Story__c>();
        
        if(!USIdSet.isEmpty()){
            for(copado__User_Story__c objUS : [select Id,No_of_Bug_Fixes__c from copado__User_Story__c where Id IN : USIdSet]){
                objUS.No_of_Bug_Fixes__c = finalcount;
                usList.add(objUS);
            }
        }
        
        system.debug('usList is ='+usList);
        Database.update(usList,false);
    }
    
}