objects/INX_Activity__c.object
<CustomObject>
    <description>Stores activities created in Infinit</description>
    <fields>
        <fullName>INX_Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>INX_Activity_Timestamp__c</fullName>
        <label>Activity timestamp</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INX_Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Close_Branch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close branch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Hash__c</fullName>
        <label>Commit (hash)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>INX_Instance__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INX_Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Needs_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Package_Directory__c</fullName>
        <label>Package directory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INX_Resolution__c</fullName>
        <label>Resolution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Source_Branch__c</fullName>
        <label>Source branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Sub_Type__c</fullName>
        <label>Sub Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Instance__c.object
<CustomObject>
    <description>Stores instances created in Infinit</description>
    <fields>
        <fullName>INX_Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Instances</relationshipLabel>
        <relationshipName>Instances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Needs_Review__c</fullName>
        <label>Needs Review</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Resolution__c.object
<CustomObject>
    <description>Stores resolution created in Infinit</description>
    <fields>
        <fullName>INX_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Hash__c</fullName>
        <label>Commit (hash)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Resolution</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Resolution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resolutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/INX_ActivitySelector.cls
public inherited sharing class INX_ActivitySelector {

    public final static List<String> lstFields = new List<String> {
        'INX_Action__c',
        'INX_Activity_Date__c',
        'INX_Activity_Timestamp__c',
        'INX_Id__c',
        'INX_Instance__c',
        'INX_Instance__r.Name',
        'INX_Repository__c',
        'INX_Repository__r.Name',
        'INX_Branch__c',
        'INX_Source_Branch__c',
        'INX_Close_Branch__c',
        'INX_Hash__c',
        'INX_Source__c',
        'INX_Message__c',
        'INX_Name__c',
        'INX_Sub_Type__c',
        'INX_Type__c',
        'INX_Email__c',
        'INX_Needs_Review__c',
        'INX_Package_Directory__c',
        'INX_Resolution__c'
    };

    public static INX_Activity__c getActivityById(String strId) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Id__c = :strId',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Activity__c'
                }
            )
        );
    }

    public static List<INX_Activity__c> getActivities(List<String> lstInstanceNames, String strAfterId) {

        INX_Activity__c sObj = getActivityById(strAfterId);

        Decimal lastActivityDate = sObj.INX_Activity_Timestamp__c;

        return getActivities(lstInstanceNames, lastActivityDate);
    }

    public static List<INX_Activity__c> getActivities(List<String> lstInstanceNames, Decimal dDatetime) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Instance__r.Name IN :lstInstanceNames AND INX_Activity_Timestamp__c >= :dDatetime ORDER BY INX_Activity_Timestamp__c LIMIT 1000',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Activity__c'
                }
            )
        );
    }

    public static List<INX_Activity__c> getActivities(List<String> lstInstanceNames) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Instance__r.Name IN :lstInstanceNames ORDER BY INX_Activity_Timestamp__c LIMIT 1000',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Activity__c'
                }
            )
        );
    }

    public static List<INX_Activity__c> getActivities(INX.Activity objActivity, Integer intLimit) {

        String type = objActivity.type;
        String subType = objActivity.subType;
        String name = objActivity.name;
        String instance = objActivity.instance;
        String repository = objActivity.repository;
        String hash = objActivity.hash;

        List<String> lstConditions = new List<String>();

        List<String> lstTypes = new List<String>();
        lstTypes.add(type);

        if('package'.equals(type)) {
            lstTypes.add('commit');
            lstTypes.add('promote');
            lstTypes.add('review');
        }

        if(String.isNotBlank(type)) {
            lstConditions.add('INX_Type__c IN :lstTypes');
        }

        if(String.isNotBlank(subType)) {
            lstConditions.add('INX_Sub_Type__c = :subType');
        }

        if(String.isNotBlank(name)) {
            lstConditions.add('INX_Name__c = :name');
        }

        if(String.isNotBlank(instance)) {
            lstConditions.add('INX_Instance__r.Name = :instance');
        }

        if(String.isNotBlank(repository)) {
            lstConditions.add('INX_Repository__r.Name = :repository');
        }

        if(String.isNotBlank(hash)) {
            lstConditions.add('INX_Hash__c = :hash');
        }

        String query = String.format(
            'SELECT {0} FROM {1} WHERE (' + String.join(lstConditions, ' AND ') + ')',
            new List<Object> {
                String.join(lstFields, ','),
                'INX_Activity__c'
            }
        );

        query += ' ORDER BY INX_Activity_Timestamp__c';

        if(intLimit != null) {
            query += ' LIMIT ' + intLimit;
        }

        return Database.query(query);
    }

    public static List<INX_Activity__c> getActivitiesForPackages(List<String> lstPackages) {

        List<String> lstConditions = new List<String>();

        List<String> lstTypes = new List<String>();
        lstTypes.add('package');
        lstTypes.add('commit');
        lstTypes.add('promote');
        lstTypes.add('review');

        lstConditions.add('INX_Type__c IN :lstTypes');
        lstConditions.add('INX_Name__c IN :lstPackages');

        String query = String.format(
            'SELECT {0} FROM {1} WHERE (' + String.join(lstConditions, ' AND ') + ')',
            new List<Object> {
                String.join(lstFields, ','),
                'INX_Activity__c'
            }
        );

        query += ' ORDER BY INX_Activity_Timestamp__c';

        return Database.query(query);
    }

    public static Integer getActivitiesCount(List<String> lstInstanceNames, String strAfterId) {

        INX_Activity__c sObj = getActivityById(strAfterId);

        Decimal lastActivityDate = sObj.INX_Activity_Timestamp__c;

        return getActivitiesCount(lstInstanceNames, lastActivityDate);
    }

    public static Integer getActivitiesCount(List<String> lstInstanceNames, Decimal dDatetime) {

        AggregateResult results = Database.query(
            String.format(
                'SELECT count(Id) result FROM {0} WHERE INX_Instance__r.Name IN :lstInstanceNames AND INX_Activity_Timestamp__c >= :dDatetime',
                new List<Object> {
                    'INX_Activity__c'
                }
            )
        );

        return Integer.valueOf(results.get('result'));
    }

    public static Integer getActivitiesCount(List<String> lstInstanceNames) {

        AggregateResult results = Database.query(
            String.format(
                'SELECT count(Id) result FROM {0} WHERE INX_Instance__r.Name IN :lstInstanceNames',
                new List<Object> {
                    'INX_Activity__c'
                }
            )
        );

        return Integer.valueOf(results.get('result'));
    }
}