objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Format__c</fullName>
        <label>Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Main_Branch__c</fullName>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Needs_Review__c</fullName>
        <label>Needs Review</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>INX_Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Remote__c</fullName>
        <label>Remote</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Source_Path__c</fullName>
        <label>Source Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INX_RepositorySelector.cls
public inherited sharing class INX_RepositorySelector {

    public final static List<String> lstFields = new List<String> {
        'Name',
        'INX_Id__c',
        'INX_Remote__c',
        'INX_Origin__c',
        'INX_Needs_Review__c',
        'INX_Main_Branch__c',
        'INX_Source_Path__c',
        'INX_Format__c',
        'INX_Is_Active__c'
    };

    public static INX_Repository__c getRepositoryByName(String strName) {

        List<INX_Repository__c> lstRepository = Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE Name = :strName',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Repository__c'
                }
            )
        );

        if(lstRepository.isEmpty()) { return null; }

        return lstRepository[0];
    }
}