objects/INX_Instance__c.object
<CustomObject>
    <description>Stores instances created in Infinit</description>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Version__c</fullName>
        <label>Version</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Package__c.object
<CustomObject>
    <description>Stores packages created in Infinit</description>
    <fields>
        <fullName>INX_Created_Date__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>INX_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Instance__c</fullName>
        <label>Instance</label>
        <referenceTo>INX_Instance__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>INX_Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>INX_Version__c</fullName>
        <label>Version</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/INX_PackageSelector.cls
public inherited sharing class INX_PackageSelector {

    public final static List<String> lstFields = new List<String> {
        'INX_Created_Date__c',
        'INX_Description__c',
        'INX_Id__c',
        'INX_Instance__c',
        'INX_Instance__r.Name',
        'INX_Last_Modified_Date__c',
        'INX_Version__c',
        'Name'
    };

    public static INX_Package__c getPackageByName(String strName) {

        List<INX_Package__c> lstPackage = Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE Name = :strName',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Package__c'
                }
            )
        );

        if(lstPackage.isEmpty()) { return null; }

        return lstPackage[0];
    }

    public static List<INX_Package__c> getPackagesByName(Set<String> setNames) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE Name IN :setNames',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Package__c'
                }
            )
        );
    }
}