objects/INX_Access__c.object
<CustomObject>
    <description>Stores Workspace and Instance access for Infinit</description>
    <fields>
        <fullName>INX_Can_Commit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can commit?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Can_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can deploy?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Can_Manage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can manage?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Can_Promote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can promote?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Can_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can read?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Instance__c</fullName>
        <label>Instance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is locked?</label>
        <type>Checkbox</type>
    </fields>
    <label>Access</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Access Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Instance__c.object
<CustomObject>
    <description>Stores instances created in Infinit</description>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INX_AccessSelector.cls
public inherited sharing class INX_AccessSelector {

    public final static List<String> lstFields = new List<String> {
        'INX_Can_Commit__c',
        'INX_Can_Deploy__c',
        'INX_Email__c',
        'INX_Instance__c',
        'INX_Can_Manage__c',
        'INX_Can_Promote__c',
        'INX_Can_Read__c',
        'INX_Is_Locked__c',
        'LastModifiedDate'
    };

    public static List<INX_Access__c> getAccessesByEmail(String strEmail) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Email__c = :strEmail ORDER BY INX_Instance__c NULLS FIRST',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Access__c'
                }
            )
        );
    }

    public static INX_Access__c getAccess(String strEmail, String strInstance) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Email__c = :strEmail AND INX_Instance__c = :strInstance',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Access__c'
                }
            )
        );
    }

    public static List<INX_Access__c> getWorkspaceAccesses() {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Instance__c = null ORDER BY INX_Email__c',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Access__c'
                }
            )
        );
    }

    public static List<INX_Access__c> getInstanceAccesses(String strInstance) {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Instance__c = :strInstance',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Access__c'
                }
            )
        );
    }
}