objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Resolution__c.object
<CustomObject>
    <description>Stores resolution created in Infinit</description>
    <fields>
        <fullName>INX_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_File_Path__c</fullName>
        <label>File Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Hash__c</fullName>
        <label>Commit (hash)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Resolution</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Resolution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resolutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/INX_ResolutionSelector.cls
public inherited sharing class INX_ResolutionSelector {

    public final static List<String> lstFields = new List<String> {
        'INX_Email__c',
        'INX_File_Path__c',
        'INX_Hash__c',
        'INX_Id__c',
        'INX_Repository__c',
        'INX_Repository__r.Name'
    };

    public static INX_Resolution__c getResolutionByHash(String strRepository, String strHash) {

        List<INX_Resolution__c> lstResolution = Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE INX_Repository__c = :strRepository AND INX_Hash__c = :strHash',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Resolution__c'
                }
            )
        );

        if(lstResolution.isEmpty()) { return null; }

        return lstResolution[0];
    }
}