objects/INX_Instance__c.object
<CustomObject>
    <description>Stores instances created in Infinit</description>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>INX_Instance__c</referenceTo>
        <relationshipLabel>Child Instances</relationshipLabel>
        <relationshipName>ChildInstances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Instances</relationshipLabel>
        <relationshipName>Instances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INX_InstanceDomain.cls
public inherited sharing class INX_InstanceDomain {

    public static void createUpdate(INX.Instance objInstance) {

        if(objInstance == null) { return; }

        INX_Instance__c sObj = objInstance.getSObject();

        if(String.isNotBlank(objInstance.repository)) {

            INX_Repository__c sObjRepository = INX_RepositorySelector.getRepositoryByName(objInstance.repository);

            sObj.INX_Repository__c = sObjRepository == null ? null : sObjRepository.Id;
        }

        if(String.isNotBlank(objInstance.parent)) {

            INX_Instance__c sObjInstance = INX_InstanceSelector.getInstanceByName(objInstance.parent);

            sObj.INX_Parent__c = sObjInstance == null ? null : sObjInstance.Id;
        }

        upsert sObj INX_Id__c;

        objInstance.remoteId = sObj.Id;
    }

    public static INX_Instance__c getInstanceByName(String strName) {

        return INX_InstanceSelector.getInstanceByName(strName);
    }

    public static INX.Instance getInstanceInfoByName(String strName) {

        INX_Instance__c sObj = getInstanceByName(strName);

        INX.Instance objInstance = null;

        if(sObj != null) {

            objInstance = new INX.Instance(sObj);
        }

        return objInstance;
    }
}