objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INX_RepositoryDomain.cls
public inherited sharing class INX_RepositoryDomain {

    public static void createUpdate(INX.Repository objRepository) {

        if(objRepository == null) { return; }

        INX_Repository__c sObj = objRepository.getSObject();

        upsert sObj INX_Id__c;

        objRepository.remoteId = sObj.Id;

    }

    public static INX_Repository__c getRepositoryByName(String strName) {

        return INX_RepositorySelector.getRepositoryByName(strName);

    }

    public static INX.Repository getRepositoryInfoByName(String strName) {

        return new INX.Repository(getRepositoryByName(strName));

    }
}