objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Resolution__c.object
<CustomObject>
    <description>Stores resolution created in Infinit</description>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Resolution</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Resolution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resolutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/INX_ResolutionDomain.cls
public inherited sharing class INX_ResolutionDomain {

    public static void createUpdate(INX.Resolution objResolutionInfo) {

        if(objResolutionInfo == null) { return; }

        INX_Resolution__c sObj = objResolutionInfo.getSObject();

        INX_Repository__c sObjRepository = INX_RepositorySelector.getRepositoryByName(objResolutionInfo.repository);

        sObj.INX_Repository__c = sObjRepository.Id;

        upsert sObj INX_Id__c;

        objResolutionInfo.remoteId = sObj.Id;

        List<INX.AttachmentDetails> lstAttachmentDetails = new List<INX.AttachmentDetails> {
            new INX.AttachmentDetails(
                objResolutionInfo.hunkDetails,
                'Resolution details',
                'Detailing resolution Hunk.'
            )
        };

        INX_Utility.processAttachments(sObj, lstAttachmentDetails);

        objResolutionInfo.hunkDetails = null;
    }

    public static INX_Resolution__c getResolutionByHash(String strRepository, String strHash) {

        return INX_ResolutionSelector.getResolutionByHash(strRepository, strHash);
    }

    public static INX.Resolution getResolutionInfoByHash(String strRepository, String strHash) {

        INX_Resolution__c sObj = getResolutionByHash(strRepository, strHash);

        INX.Resolution objResolution = null;

        if(sObj != null) {

            objResolution = new INX.Resolution(sObj);

            List<INX.AttachmentDetails> lstAttachmentDetails = new List<INX.AttachmentDetails> {
                new INX.AttachmentDetails('Resolution details')
            };

            INX_Utility.getFromAttachments(objResolution, sObj, lstAttachmentDetails);
        }

        return objResolution;
    }
}