objects/INX_Instance__c.object
<CustomObject>
    <description>Stores instances created in Infinit</description>
    <fields>
        <fullName>INX_Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Credentials__c</fullName>
        <label>Credentials</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>INX_Deployment_Settings__c</fullName>
        <label>Deployment settings</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>INX_Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Jira_Settings__c</fullName>
        <label>Jira settings</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>INX_OrgId__c</fullName>
        <label>OrgId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>INX_Instance__c</referenceTo>
        <relationshipLabel>Child Instances</relationshipLabel>
        <relationshipName>ChildInstances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INX_Promote_Settings__c</fullName>
        <label>Promote settings</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>INX_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repository</label>
        <referenceTo>INX_Repository__c</referenceTo>
        <relationshipLabel>Instances</relationshipLabel>
        <relationshipName>Instances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>INX_Share_Credentials__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Share credentials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>INX_Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INX_Version__c</fullName>
        <label>Version</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INX_Repository__c.object
<CustomObject>
    <fields>
        <fullName>INX_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>INX_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INX_InstanceSelector.cls
public inherited sharing class INX_InstanceSelector {

    public final static List<String> lstFields = new List<String> {
        'Name',
        'INX_Endpoint__c',
        'INX_Id__c',
        'INX_Is_Active__c',
        'INX_OrgId__c',
        'INX_Version__c',
        'INX_Username__c',
        'INX_Credentials__c',
        'INX_Share_Credentials__c',
        'INX_Parent__c',
        'INX_Parent__r.Name',
        'INX_Repository__c',
        'INX_Repository__r.Name',
        'INX_Branch__c',
        'INX_Deployment_Settings__c',
        'INX_Promote_Settings__c',
        'INX_Jira_Settings__c'
    };

    public static List<INX_Instance__c> getInstances() {

        return Database.query(
            String.format(
                'SELECT {0} FROM {1} ORDER BY Name',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Instance__c'
                }
            )
        );
    }

    public static INX_Instance__c getInstanceByName(String strName) {

        List<INX_Instance__c> lstInstance = Database.query(
            String.format(
                'SELECT {0} FROM {1} WHERE Name = :strName',
                new List<Object> {
                    String.join(lstFields, ','),
                    'INX_Instance__c'
                }
            )
        );

        if(lstInstance.isEmpty()) { return null; }

        return lstInstance[0];
    }
}